### PR TITLE
deploy to gh pages

### PR DESCRIPTION
**Pull request by pavelskipenes**

### CODE REVIEW

**Comment by pavelskipenes** [comment]
image
@Sigevio can you enable github pages in settings of this repository? Branch name needs to be `gh-pages`.

**Comment by Sigevio** [comment]
Done.

**Comment by pavelskipenes** [comment]
Hmm. Something is not working right :P https://sigevio.github.io/ntnui-swimming-frontend/

**Comment by pavelskipenes** [comment]
```log
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: next-export-i18n@2.0.3
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.10.0
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.10.0" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.10.0
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.10.0" from the root project
npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!     4 more (@mui/material, @mui/styled-engine, @mui/system, react-awesome-reveal)
npm ERR!   16 more (@emotion/styled, @mui/base, @mui/icons-material, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.0.0" from next-export-i18n@2.0.3
npm ERR! node_modules/next-export-i18n
npm ERR!   next-export-i18n@"^2.0.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from next-export-i18n@2.0.3
npm ERR!   node_modules/next-export-i18n
npm ERR!     next-export-i18n@"^2.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-08-07T19_51_05_330Z-debug-0.log
```

**Comment by pavelskipenes** [comment]
fuck

**Comment by Sigevio** [comment]
> fuck

:(

**Comment by pavelskipenes** [comment]
I think this is the issue
> While `assetPrefix` covers requests to `_next/static`, it does not influence the following paths:
> 
> - Files in the [public](https://nextjs.org/docs/basic-features/static-file-serving) folder; if you want to serve those assets over a CDN, you'll have to introduce the prefix yourself
> - `/_next/data/` requests for `getServerSideProps` pages. These requests will always be made against the main domain since they're not static.
> - `/_next/data/` requests for `getStaticProps` pages. These requests will always be made against the main domain to support [Incremental Static Generation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), even if you're not using it (for consistency).

**Comment by Sigevio** [comment]
Try to remove the Fade-components from the home page.

**Comment by Sigevio** [comment]
https://www.linkedin.com/pulse/deploy-nextjs-app-github-pages-federico-antu%C3%B1a/

**Pull request closed without merging**
