### PR TITLE
Change header font and add margin to 'slogan'

### PR DESCRIPTION
**Pull request by Sigevio**

### CODE REVIEW

**Review by pavelskipenes — CHANGES_REQUESTED** [review]
```
❯ npm run build && npm run start

> frontend@0.1.0 build
> next build

info  - Checking validity of types  
error - ESLint: Failed to load config "next/babel" to extend from. Referenced from: /home/pavel/repos/external/org.ntnu.svommer/.eslintrc.json
info  - Creating an optimized production build  
Failed to compile.

./pages/_app.tsx
Module not found: Can't resolve '@fontsource/montserrat/300.css' in '/home/pavel/repos/external/org.ntnu.svommer/pages'

./pages/_app.tsx
Module not found: Can't resolve '@fontsource/montserrat/400.css' in '/home/pavel/repos/external/org.ntnu.svommer/pages'

./pages/_app.tsx
Module not found: Can't resolve '@fontsource/montserrat/500.css' in '/home/pavel/repos/external/org.ntnu.svommer/pages'

./pages/_app.tsx
Module not found: Can't resolve '@fontsource/montserrat/700.css' in '/home/pavel/repos/external/org.ntnu.svommer/pages'


> Build failed because of webpack errors

```

**Comment by Sigevio** [comment]
run "npm i" to install new dependency

**Comment by pavelskipenes** [comment]
> run "npm i" to install new dependency

```
❯ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @mui/icons-material@5.5.1
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.8.2
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.8.2" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.8.1
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.8.1" from the root project
npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!     4 more (@mui/material, @mui/styled-engine, @mui/system, react-awesome-reveal)
npm ERR!   14 more (@emotion/styled, @mui/base, @mui/private-theming, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from @mui/icons-material@5.5.1
npm ERR! node_modules/@mui/icons-material
npm ERR!   @mui/icons-material@"^5.5.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.0" from @mui/icons-material@5.5.1
npm ERR!   node_modules/@mui/icons-material
npm ERR!     @mui/icons-material@"^5.5.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/pavel/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pavel/.npm/_logs/2022-08-05T22_44_27_094Z-debug-0.log

```

**Comment by pavelskipenes** [comment]
Should probably add some CI to this repo...

**Comment by Sigevio** [comment]
probably.. try "npm i --legacy-peer-deps" for now

**Comment by pavelskipenes** [comment]
Seems like the subtitle is not properly centered
image
Mobile looks fine

**Comment by Sigevio** [comment]
Sub title with margin was intentional. Does it not look good?

**Comment by pavelskipenes** [comment]
> Sub title with margin was intentional. Does it not look good?

I personally find it a bit odd, but if you prefer it that way that should be your call.

**Review by pavelskipenes — APPROVED** [review]

**Pull request merged**
